opendxp:
    documents:
        web_to_print:
            enableInDefaultView: false
            generalTool: wkhtmltopdf
            generalDocumentSaveMode: default
            pdfreactorProtocol: https
            pdfreactorServer: localhost
            pdfreactorServerPort: '443'
            pdfreactorBaseUrl: 'http://my.domain.com'
            pdfreactorApiKey: ''
            pdfreactorLicence: ''
            pdfreactorEnableLenientHttpsMode: false
            pdfreactorEnableDebugMode: false
            headlessChromeSettings: ''