Listen 31001

<VirtualHost *:31001>
    DocumentRoot /var/www/html/app/slot-1/public

    <Directory "/var/www/html/app/slot-1/public/">
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /dev/stdout
    CustomLog /dev/null combined
</VirtualHost>

Listen 31002

<VirtualHost *:31002>
    DocumentRoot /var/www/html/app/slot-2/public

    <Directory "/var/www/html/app/slot-2/public/">
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /dev/stdout
    CustomLog /dev/null combined
</VirtualHost>

Listen 31003

<VirtualHost *:31003>
    DocumentRoot /var/www/html/app/slot-3/public

    <Directory "/var/www/html/app/slot-3/public/">
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /dev/stdout
    CustomLog /dev/null combined
</VirtualHost>

Listen 31004

<VirtualHost *:31004>
    DocumentRoot /var/www/html/app/slot-4/public

    <Directory "/var/www/html/app/slot-4/public/">
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /dev/stdout
    CustomLog /dev/null combined
</VirtualHost>

Listen 31005

<VirtualHost *:31005>
    DocumentRoot /var/www/html/app/slot-5/public

    <Directory "/var/www/html/app/slot-5/public/">
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /dev/stdout
    CustomLog /dev/null combined
</VirtualHost>

Listen 31006

<VirtualHost *:31006>
    DocumentRoot /var/www/html/app/slot-6/public

    <Directory "/var/www/html/app/slot-6/public/">
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /dev/stdout
    CustomLog /dev/null combined
</VirtualHost>

Listen 31007

<VirtualHost *:31007>
    DocumentRoot /var/www/html/app/slot-7/public

    <Directory "/var/www/html/app/slot-7/public/">
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /dev/stdout
    CustomLog /dev/null combined
</VirtualHost>

Listen 31008

<VirtualHost *:31008>
    DocumentRoot /var/www/html/app/slot-8/public

    <Directory "/var/www/html/app/slot-8/public/">
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /dev/stdout
    CustomLog /dev/null combined
</VirtualHost>

Listen 31009

<VirtualHost *:31009>
    DocumentRoot /var/www/html/app/slot-9/public

    <Directory "/var/www/html/app/slot-9/public/">
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /dev/stdout
    CustomLog /dev/null combined
</VirtualHost>

Listen 31010

<VirtualHost *:31010>
    DocumentRoot /var/www/html/app/slot-10/public

    <Directory "/var/www/html/app/slot-10/public/">
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /dev/stdout
    CustomLog /dev/null combined
</VirtualHost>

