parameters:
    secret: ThisTokenIsNotSoSecretChangeIt

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Controller\:
        resource: '../src/Controller'
        public: true
        tags: [ 'controller.service_arguments' ]

    App\Command\:
        resource: '../src/Command/*'
        tags: [ 'console.command' ]
