#!/usr/bin/env bash

## Description: Run OpenDXP Tests
## Usage: opendxp-tests-dispatcher
## Example: "ddev opdenxp-tests-dispatcher"
set -e

APP_IP="$(ip addr show eth0 | grep 'inet\b' | awk '{print $2}' | cut -d/ -f1)"

export WEBDRIVER_HOST="selenium-chrome"
export WEBDRIVER_URL="http://$APP_IP/"

while :
do
    case "$1" in
        codecept)
            echo ""
            echo "*************************************************************************"
            echo "run codeception tests"
            echo "*************************************************************************"
            cd /var/www/html/app
            /usr/bin/php -d memory_limit=-1 vendor/bin/codecept run -c . --env local "${@:2}"
            cd ~-
            exit
            ;;
        codecept-xdebug)
            echo ""
            echo "*************************************************************************"
            echo "run codeception tests with xdebug"
            echo "*************************************************************************"
            echo ""
            cd /var/www/html/app
            PHP_IDE_CONFIG="serverName=opendxp.test" /usr/bin/php -dxdebug.remote_enable=1 -dxdebug.remote_autostart=On -dxdebug.idekey=PHPSTORM -dxdebug.remote_host=$2 -d memory_limit=-1 -d memory_limit=-1 vendor/bin/codecept run -c . --env local "${@:3}"
            cd ~-
            exit
            ;;
        phpstan)
            echo ""
            echo "*************************************************************************"
            echo "run phpstan"
            echo "*************************************************************************"
            echo ""
            cd /var/www/html/app
            bin/console cache:warmup --env=test --no-optional-warmers
            php -d memory_limit=-1 vendor/bin/phpstan analyse -c phpstan.neon -a tests/_phpstan-bootstrap.php src "${@:2}"
            cd ~-
            exit
            ;;
        cs-fixer)
            echo ""
            echo "*************************************************************************"
            echo "run cs-fixer"
            echo "*************************************************************************"
            echo "Currently not supported"
            exit
            ;;
        *)
            echo "Usage: $(basename $0) tests|tests-enable-xdebug|tests-xdebug|phpstan|cs-fixer [args]"
            exit
            ;;
    esac
done
