#!/usr/bin/env bash

## Description: Run Composer in Test environment
## Usage: opendxp-tests-composer
## Example: "ddev opendxp-tests-composer d"

cd /var/www/html/app

if jq -e '.suggest' composer.json > /dev/null; then

    packages=$(jq -r '.suggest | to_entries | map("\(.key):\(.value)") | join(" ")' composer.json)

    if [ -n "$packages" ]; then
        composer require $packages -W --no-progress --no-update
    else
        echo "No packages found in the suggest section."
    fi
else
    echo "No suggest section found in composer.json."
fi

## Set Dynamic Search Dependency to branch alias (@todo: not here!)
#sed -i 's,\("open-dxp\/dynamic-search-bundle"\): "\(.*\)",\1: "1.x-dev",g' composer.json

## Set Composer Root Version (@todo)
#export COMPOSER_ROOT_VERSION=1.x-dev

## Configure Composer Auth
export COMPOSER_AUTH="{\"github-oauth\": {\"github.com\": \"$GITHUB_PRIVATE_ACCESS_TOKEN\"}}"

## Add Repman Repository Link
composer config repositories.opendxp '{"type": "composer", "url": "https://open-dxp.repo.repman.io"}' --file composer.json

## Update Composer Dependencies
composer update --no-progress --no-scripts

./bin/console cache:clear --no-interaction
./bin/console assets:install public --relative --symlink