name: opendxp-docker-testkit
type: php
docroot: app/public
php_version: "8.3"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
composer_version: "2"
webimage: docker.dachcom.net/docker/ddev-base:latest
additional_fqdns:
    - 'opendxp-testing.test'
additional_hostnames:
    - 'test-domain1.test'
    - 'test-domain2.test'
    - 'test-domain3.test'
    - 'test-domain4.test'
    - 'test-domain5.test'
    - 'test-domain6.test'
    - 'test-domain7.test'
database:
    type: mysql
    version: '8.4'
hooks:
    pre-start:
        -   exec-host: "echo 'Booting Test System'"
        -   exec-host: "[ -d app ] && rm -rf app || true; mkdir -p app"
        -   exec-host: "mkdir -p app/public"
        -   exec-host: "touch app/public/index.php"
        -   exec-host: "export $(grep -v '^#' .ddev/.env | xargs) && ln -sfn $OPENDXP_CODECEPTION_FRAMEWORK_LOCAL_PATH app/opendxp-codeception-framework"

web_environment:

    - TEST_EXECUTE_COMPOSER=${TEST_EXECUTE_COMPOSER:-false}

    - APP_ENV=test
    - SYMFONY_DEPRECATIONS_HELPER=weak

    - OPENDXP_PROJECT_ROOT=/var/www/html/app
    - OPENDXP_CODECEPTION_FRAMEWORK_PATH=/tmp/opendxp-codeception-framework

    - WEBDRIVER_DOWNLOAD_PATH=/home/seluser/Downloads

    - OPENDXP_TEST_DB_DSN=mysql://db:db@db:3306/db
    - OPENDXP_INSTALL_MYSQL_DATABASE=db
    - OPENDXP_INSTALL_MYSQL_USERNAME=db
    - OPENDXP_INSTALL_MYSQL_PASSWORD=db
    - OPENDXP_INSTALL_ADMIN_USERNAME=db
    - OPENDXP_INSTALL_ADMIN_PASSWORD=db
    - OPENDXP_INSTALL_MYSQL_HOST_SOCKET=db

