services:
    selenium-chrome:
        image: selenium/standalone-chrome:latest
        container_name: ddev-${DDEV_SITENAME}-selenium-chrome
        expose:
            - 7900
        environment:
            - VIRTUAL_HOST=$DDEV_HOSTNAME
            - HTTPS_EXPOSE=7900:7900
            - HTTP_EXPOSE=7910:7900
        external_links:
            - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}
        labels:
            com.ddev.site-name: ${DDEV_SITENAME}
            com.ddev.approot: $DDEV_APPROOT
        volumes:
            - ".:/mnt/ddev_config"
            # Headless chrome ignores the download directory it is configured with and writes to
            # its own. Point that at the directory seeDownload() reads from.
            - "${DDEV_APPROOT}/.ddev/downloads:/home/seluser/Downloads"
    web:
        links:
            - selenium-chrome
        environment:
            - WEBDRIVER_DOWNLOAD_PATH=/home/seluser/Downloads
            - BROWSERTEST_OUTPUT_DIRECTORY=/tmp
            - BROWSERTEST_OUTPUT_BASE_URL=${DDEV_PRIMARY_URL}
            - SIMPLETEST_BASE_URL=http://web
            - SIMPLETEST_DB=mysql://db:db@db/db
